### ISSUE TITLE
Webpack error: 141:29-43 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by PDS42** [Marak/colors.js#200] opened 2017-08-07 07:50 UTC
Hello, I've been struggling with this issue for a few days now. What's bothering me here is the following error: `WARNING in ./node_modules/colors/lib/colors.js  141:29-43 Critical dependency: the request of a dependency is an expression`. I can make the other errors go away, but not this one. From what I've read so far, a dynamic `require` might cause this issue. I'm really unsure how to fix this. Any help appreciated! 

![Screenshot of the error](https://user-images.githubusercontent.com/11089426/29017100-b0295d3c-7b55-11e7-8600-a2e3d91ae9d5.png)

**Comment by jpap** [comment] 2017-09-29 22:29
You're exactly right; the warning is a result of the `setTheme` method below, and is caused by the `require(theme)` in the `try`-block.

```js
colors.setTheme = function (theme) {
  if (typeof theme === 'string') {
    try {
      colors.themes[theme] = require(theme);
      applyTheme(colors.themes[theme]);
      return colors.themes[theme];
    } catch (err) {
      console.log(err);
      return err;
    }
  } else {
    applyTheme(theme);
  }
};
```

I'd love if there was a way to silence the webpack warning as it is otherwise tarnishing a clean build -- this package is a dependency of winston which I am using in a project.

**Comment by jpap** [comment] 2017-09-29 23:00
I'd say this is a dupe of #137 and can be closed...

**Comment by DABH** [comment] 2018-02-12 18:33
Going to close this in favor of #137 , and hopefully resolve the issue over there... thanks for the discussion on this!

**Closed by DABH** 2018-02-12 18:33 UTC
Labels: duplicate
