### ISSUE TITLE
loooooooooooooooooooooop

### ISSUE THREAD

**Issue by novenn** [Marak/colors.js#294] opened 2022-01-10 06:41 UTC
what is this

![image](https://user-images.githubusercontent.com/24600592/148726804-205b2cf3-e1c4-45e6-b8a4-fa75d4bbc81c.png)

**Comment by SudoUserReal** [comment] 2022-01-10 06:43
See the news。

**Comment by jiaoguanwen** [comment] 2022-01-10 06:44
same

**Comment by santigp258** [comment] 2022-01-10 06:44
Check [this](https://github.com/Marak/colors.js/issues/285#issuecomment-1008168237)

**Comment by flying-ostrich** [comment] 2022-01-10 06:45
out of mind ?

**Comment by zagfai** [comment] 2022-01-10 06:56
Support U guy.

**Comment by novenn** [comment] 2022-01-10 07:01
i have fixed it and publish to our private repo

**Comment by huqiliang** [comment] 2022-01-10 07:11
you fucked everyone the same with you.

**Comment by karikera** [comment] 2022-01-10 09:42
1.4.1 and 1.4.2
1.4.0 is working

**Comment by euberdeveloper** [comment] 2022-01-10 10:02
Hi, in case the author will not maintain this project or fix this, I made a fork that restores the normal behaviour. I am not sure if I will maintain this package, but just in case the problem will not be solved and you don't want to be scared when running `npm update`...

https://github.com/euberdeveloper/colors.js

In any case I could also suggest passing to the chalk package, which is very good and has a serious and reliable author

**Comment by karikera** [comment] 2022-01-10 10:56
Duplicate of #289

**Comment by dutziworks** [comment] 2022-01-10 10:57
Idiot.

**Comment by RIAEvangelist** [comment] 2022-01-10 16:56
LOL, that's the first time I saw the code. Despite what it has done, that is kind of funny because it is so obvious.

This is technically within his rights according to the license.

Here is an alternative if you don't want to fork or do it on your own:

`nozaki-colors` https://github.com/RIAEvangelist/nozaki-colors

**Comment by G2G2G2G** [comment] 2022-01-10 18:42
i = 666
wow I knew the devil was behind this mischief

**Closed as completed** 2022-01-19 05:03 UTC
