### ISSUE TITLE
String.prototype.bold not compatible with ES6

### ISSUE THREAD

**Issue by panuhorsmalahti** [Marak/colors.js#110] opened 2015-02-16 12:42 UTC
ES6 brings String.prototype.bold to wrap string to bold tags:
https://javascript.spec.whatwg.org/#string.prototype.bold

However, colors.js also wants to use that property. I recommend renaming the .bold property to something else.

**Comment by plantain-00** [comment] 2015-12-10 10:19
+1

**Comment by RichardSimko** [comment] 2016-03-15 12:27
+1 this breaks compatibility with ES6

**Comment by AppShipIt** [comment] 2016-05-16 21:10
It looks deprecated?

**Comment by DABH** [comment] 2018-02-17 06:58
ES6 deprecates that though... so, is there a way to keep the name bold in colors while not causing conflicts with the prototype method?  Ideas welcome.  Would be great to not have to change the colors API, especially for a deprecated function.  Note this should only be an issue outside safe mode for colors.

**Comment by DABH** [comment] 2018-02-22 05:02
I'm closing this as a duplicate of #168 , but this isn't solved yet, so really encourage discussion on that issue.  Would be great to find a workaround^^

**Closed by DABH** 2018-02-22 05:02 UTC
