### ISSUE TITLE
Strikethrough is not working.

### ISSUE THREAD

**Issue by c-ro** [Marak/colors.js#159] opened 2016-04-26 16:11 UTC
Have tried:
`colors.red.strikethrough("blah blah blah)`
`colors.red("blah blah blah).strikethrough`
`"blah blah blah".strikethrough`
`colors.strikethrough("blah blah blah")`

**Comment by DABH** [comment] 2018-02-12 21:45
Works for me (Node 8.9.4, npm 5.6.0, bash terminal).  Moreover strikethrough is covered in the unit tests, which all pass.  Can you provide more info on how to reproduce?  Is this still an issue for you?

**Comment by DABH** [comment] 2018-02-21 04:35
Closing this for now, feel free to re-open if it's still an issue with latest versions of everything (including `colors@next`)

**Closed by DABH** 2018-02-21 04:35 UTC
Labels: can't reproduce
